=== DDavid112/OP9WROWebXML/1014/OP9WRO_XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!-- Egyszerű típusok - felépítés -->

<xs:element name="OP9WRO_vendeglatas">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="etterem" type="etteremTipus" maxOccurs="unbounded"/>
            <xs:element name="foszakacs" type="foszakacsTipus" maxOccurs="unbounded"/>
            <xs:element name="szakacs" type="szakacsTipus" maxOccurs="unbounded"/>
            <xs:element name="gyakornok" type="gyakornokTipus" maxOccurs="unbounded"/>
            <xs:element name="vendeg" type="vendegTipus" maxOccurs="unbounded"/>
            <xs:element name="rendeles" type="rendelesTipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>



<!-- pk kulcsok-->
<xs:key name="etterem_kulcs">
    <xs:selector xpath="etterem"/>
    <xs:field xpath="@ekod"/>
</xs:key>

<xs:key name="foszakacs_kulcs">
    <xs:selector xpath="foszakacs"/>
    <xs:field xpath="@fkod"/>
</xs:key>

<xs:key name="szakacs_kulcs">
    <xs:selector xpath="szakacs"/>
    <xs:field xpath="@szkod"/>
</xs:key>

<xs:key name="gyakornok_kulcs">
    <xs:selector xpath="gyakornok"/>
    <xs:field xpath="@gykod"/>
</xs:key>

<xs:key name="vendeg_kulcs">
    <xs:selector xpath="vendeg"/>
    <xs:field xpath="@vkod"/>
</xs:key>

<!-- idegen kulcsok-->
<xs:keyref refer="etterem_kulcs" name="etterem_idegen_kulcs">
    <xs:selector xpath="rendeles"/>
    <xs:field xpath="@e_v_e"/>
</xs:keyref>
<xs:keyref refer="vendeg_kulcs" name="vendeg_idegen_kulcs">
    <xs:selector xpath="rendeles"/>
    <xs:field xpath="@e_v_v"/>
</xs:keyref>

<xs:keyref refer="etterem_kulcs" name="etterem_foszakacs_idegen_kulcs">
    <xs:selector xpath="foszakacs"/>
    <xs:field xpath="@e_f"/>
</xs:keyref>

<xs:keyref refer="etterem_kulcs" name="etterem_szakacs_idegen_kulcs">
    <xs:selector xpath="szakacs"/>
    <xs:field xpath="@e_sz"/>
</xs:keyref>

<xs:keyref refer="etterem_kulcs" name="etterem_gyakornok_idegen_kulcs">
    <xs:selector xpath="gyakornok"/>
    <xs:field xpath="@e_gy"/>
</xs:keyref>



<!-- 1:1 kapcsolat megvalósítása-->
 <xs:unique name="unique_foszakacs">
    <xs:selector xpath="foszakacs"/>
    <xs:field xpath="@e_f"/>
 </xs:unique>

 </xs:element>





<!-- komplex ítpusok-->
<xs:complexType name="etteremTipus">
    <xs:sequence>
        <xs:element name="nev" type="xs:string"/>
        <xs:element name="cim" type="cimTipus"/>
        <xs:element name="csillag" type="xs:integer"/>
    </xs:sequence>
    <xs:attribute name="ekod" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="cimTipus">
    <xs:sequence>
        <xs:element name="varos" type="xs:string"/>
        <xs:element name="utca" type="xs:string"/>
        <xs:element name="hazszam" type="xs:integer"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="foszakacsTipus">
    <xs:sequence>
        <xs:element name="nev" type="xs:string"/>
        <xs:element name="eletkor" type="xs:integer"/>
        <xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="fkod" type="xs:string" use="required"/>
    <xs:attribute name="e_f" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="szakacsTipus">
    <xs:sequence>
        <xs:element name="nev" type="xs:string"/>
        <xs:element name="reszleg" type="xs:string"/>
        <xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="szkod" type="xs:string" use="required"/>
    <xs:attribute name="e_sz" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="gyakornokTipus">
    <xs:sequence>
        <xs:element name="nev" type="xs:integer"/>
        <xs:element name="gyakorlat" type="gyakorlatTipus"/>
        <xs:element name="muszak" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="gykod" type="xs:string" use="required"/>
    <xs:attribute name="e_gy" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="gyakorlatTipus">
    <xs:sequence>
        <xs:element name="kezdete" type="xs:string"/>
        <xs:element name="idotartama" type="xs:string"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="vendegTipus">
    <xs:sequence>
        <xs:element name="nev" type="xs:string"/>
        <xs:element name="eletkor" type="xs:integer"/>
        <xs:element name="cim" type="cimTipus"/>
    </xs:sequence>
    <xs:attribute name="vkod" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="rendelesTipus">
    <xs:sequence>
        <xs:element name="osszeg" type="xs:string"/>
        <xs:element name="etel" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="e_v_v" type="xs:string" use="required"/>
    <xs:attribute name="e_v_e" type="xs:string" use="required"/>
</xs:complexType>





</xs:schema>

=== DDavid112/OP9WROWebXML/DomParseOP9WRO/out/production/DomParseOP9WRO/OP9WRO_XML.xml
<?xml version="1.0" encoding="UTF-8"?>

<OP9WRO_vendeglatas xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="OP9WRO_XMLSchema.xsd">

<!--Ettermek-->
<etterem ekod="e1">
    <nev>Trófea</nev>
    <cim>
        <varos>Budapest</varos>
        <utca>Visegrádi</utca>
        <hazszam>4</hazszam>
    </cim>
    <csillag>4</csillag>
</etterem>

<etterem ekod="e2">
    <nev>Gundel</nev>
    <cim>
        <varos>Budapest</varos>
        <utca>Gundel Károly</utca>
        <hazszam>16</hazszam>
    </cim>
    <csillag>5</csillag>
</etterem>

<foszakacs fkod="f1" e_f="e1">
    <nev>Kovács Géza</nev>
    <eletkor>34</eletkor>
    <vegzettseg>Le Cordon Bleu</vegzettseg>
</foszakacs>

<foszakacs fkod="f2" e_f="e2">
    <nev>Papp Győző</nev>
    <eletkor>41</eletkor>
    <vegzettseg>Szakközépsikola</vegzettseg>
     <vegzettseg>Le Cordon Bleu</vegzettseg>
</foszakacs>


<szakacs szkod="sz1" e_sz="esz1">
    <nev>Horvát Linda</nev>
    <reszleg>Krumplipucolás</reszleg>
    <vegzettseg>Szakközépsikola</vegzettseg>
</szakacs>

<szakacs szkod="sz2" e_sz="esz2">
    <nev>Lakatos Elemér</nev>
    <reszleg>Levesek</reszleg>
    <vegzettseg>nincs</vegzettseg>
</szakacs>

<szakacs szkod="sz3" e_sz="esz3">
    <nev>Melon Musk</nev>
    <reszleg>Mártások készítése</reszleg>
    <vegzettseg>Tokaji Borászati Egyetem Mesterfok</vegzettseg>
</szakacs>

<szakacs szkod="sz4" e_sz="esz4">
    <nev>Molnár Eszter</nev>
    <reszleg>Húsok</reszleg>
    <vegzettseg>Gimnázium</vegzettseg>
    <vegzettseg>Egri Egyetem Mesterfok</vegzettseg>
</szakacs>

<gyakornok gykod="gy1" e_gy="egy1">
    <nev>Mr.Bean</nev>
    <muszak>Délután</muszak>
    <gyakorlat>
        <kezdete>2026.09.12</kezdete>
        <idotartama>9 hónap</idotartama>
    </gyakorlat>
</gyakornok>

<gyakornok gykod="gy2" e_gy="egy3">
    <nev>Kiss Tünde</nev>
    <muszak>Délelőtt</muszak>
    <gyakorlat>
        <kezdete>2026.07.18</kezdete>
        <idotartama>10 hónap</idotartama>
    </gyakorlat>
</gyakornok>

<vendeg vkod="v1">
    <nev>Fehér Ferenc</nev>
    <eletkor>56</eletkor>
    <cim>
        <varos>Mezőkövesd</varos>
        <utca>Petőfi Sándor</utca>
        <hazszam>48</hazszam>
    </cim>
</vendeg>

<vendeg vkod="v2">
    <nev>Mia Khalifa</nev>
    <eletkor>32</eletkor>
    <cim>
        <varos>Tel Aviv</varos>
        <utca>Big Yahu</utca>
        <hazszam>19</hazszam>
    </cim>
</vendeg>

<vendeg vkod="v3">
    <nev>Tóth Tibor</nev>
    <eletkor>15</eletkor>
    <cim>
        <varos>Veszprém</varos>
        <utca>Kossuth Lajos</utca>
        <hazszam>23</hazszam>
    </cim>
</vendeg>

<rendeles e_v_v="e1" e_v_e="v1">
    <osszeg>21325</osszeg>
    <etel>Harcsapaprikás</etel>
</rendeles>

<rendeles e_v_v="e2" e_v_e="v2">
    <osszeg>9990</osszeg>
    <etel>Töltött Káposzta</etel>
</rendeles>


<rendeles e_v_v="e1" e_v_e="v2">
    <osszeg>6700</osszeg>
    <etel>Rántott Karfiol Kuszkusszal</etel>
</rendeles>

<rendeles e_v_v="e2" e_v_e="v3">
    <osszeg>299</osszeg>
    <etel>Mackó Sajt</etel>
</rendeles>


</OP9WRO_vendeglatas>
